---
title: "Recent Activity Summary"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, error = FALSE, cache = FALSE)
library(tidyverse)
library(lubridate)
library(edwards)
library(knitr)
library(kableExtra)
source("../functions.R")
theme_set(cowplot::theme_minimal_grid())
```

```{r dates}
last_week <- last_complete_week(today())
week_starts <- seq(last_week[1] - 77, last_week[1], by = "week")
```

```{r dt_all}
dt_all <- readRDS("../data_processed/log_all.RDS") 
```

```{r dt}
start_date <- week_starts[1]
end_date <- last_week[7]
dt <- dt_all %>% 
  filter(between(date, start_date, end_date)) %>% 
  select(-week_data) %>% 
  mutate(week = floor_date(date, unit = "weeks", week_start = 1))
```

```{r totals}
totals <- readRDS("../data_processed/totals.RDS")
```

```{r week_totals}
week_totals <- group_by(dt, week, type) %>% 
  summarise(across(c(time, distance, ascent), sum)) %>% 
  ungroup() %>% 
  pivot_longer(time:ascent, names_to = "metric", cols_vary = "slowest") %>% 
  complete(week, type, metric, fill = list(value = 0))
tot_hrs <- week_totals %>% 
  filter(metric == "time") %>% 
  mutate(hours = value / 60)
all_hrs <- tot_hrs %>% 
  group_by(week) %>% 
  summarise(hours = sum(hours)) %>% 
  mutate(type = "All")
```

A summary of activities for `r length(week_starts)` weeks from `r start_date` to `r end_date` (inclusive).

I did `r nrow(dt)` activities.

```{r week_means}
dt %>% 
  group_by(type) %>% 
  summarise(n_total = n(), n = round(n() / 12, 2), across(c(time, distance, ascent), ~round(sum(.) / 12, 0))) %>% 
  my_kable(caption = "Weekly averages for last 12 full weeks.")
```

# This Year

```{r 23_weeks}
n_weeks <- yday(end_date) / 7
```

```{r 23_all}
dt_all %>% 
  filter(year(date) == 2023) %>% 
  group_by(type) %>% 
  summarise(n = n(), across(c(time, distance, ascent), sum)) %>% 
  mutate(n_wkly = round(n/n_weeks, 2), 
         across(c(time, distance, ascent), ~round(./n_weeks, 0), .names = "{.col}_wkly")) %>% 
  my_kable(caption = "Totals for this year so far.")
```

```{r 23_bike}
dt_all %>% 
  filter(type == "B", year(date) == 2023) %>% 
  group_by(subtype) %>% 
  summarise(n = n(), across(c(time, distance, ascent), sum)) %>% 
  mutate(n_wkly = round(n/n_weeks, 2), 
         across(c(time, distance, ascent), ~round(./n_weeks, 0), .names = "{.col}_wkly")) %>% 
  my_kable(caption = "Totals by bike for this year so far.")
```

# Hours by Week

```{r hours1}
tot_hrs %>% 
  bind_rows(all_hrs) %>% 
  ggplot(aes(week, hours, group = type, col = type)) +
  geom_line() +
  geom_point() +
  labs(x = "Week", y = "Hours", title = "Activity Time by Type")
```

```{r hours2}
tot_hrs %>% 
  mutate(type = factor(type, c("F", "B", "R"))) %>% 
  ggplot(aes(week, hours, group = type, fill = type)) +
  geom_col(position = "dodge") +
  labs(x = "Week", y = "Hours", title = "Activity Time by Type")
```

```{r hours3}
tot_hrs %>% 
  mutate(type = factor(type, c("F", "B", "R"))) %>% 
  ggplot(aes(week, hours, group = type, fill = type)) +
  geom_col() +
  labs(x = "Week", y = "Hours", title = "Activity Time by Type")
```

```{r hours4, include = FALSE}
tot_hrs %>% 
  group_by(week) %>% 
  summarise(hours = sum(hours)) %>% 
  ggplot(aes(week, hours)) +
  geom_col() +
  geom_label(aes(label = round(hours, 1))) +
  labs(x = "Week", y = "Hours", title = "Total Activity Time")
```

# Distance and Ascent

```{r distance}
week_totals %>% 
  filter(type %in% c("F", "R"),
         metric == "distance") %>% 
  mutate(type = factor(type, c("F", "R"))) %>% 
  ggplot(aes(week, value, group = type, fill = type)) +
  geom_col() +
  labs(x = "Week", y = "Distance (km)", title = "Foot Distance")
```

```{r ascent}
week_totals %>% 
  filter(metric == "ascent") %>% 
  mutate(type = factor(type, c("F", "B", "R"))) %>% 
  ggplot(aes(week, value, group = type, fill = type)) +
  geom_col() +
  labs(x = "Week", y = "Ascent (m)", title = "Ascent by Type")
```

# Training Load

These show 2023 only, up to `r max(totals$date)`.


```{r tl1}
plot_tl(totals, hours, 2023, types = "frb") + ggtitle("All Activities")
plot_tl(totals, hours, 2023, types = "r") + ggtitle("Running Only")
plot_tl(totals, hours, 2023, types = "b") + ggtitle("Cycling Only")
plot_tl(totals, ascent, 2023, types = "frb")
plot_tl(totals, aer, 2023, types = "frb")
```

# Main Activities

Longest 2 activities in the last 6 weeks for each activity type.

```{r dt_most}
dt_most <- dt %>% 
  mutate(weeks_since = isoweek(end_date) - isoweek(date)) %>%
  filter(weeks_since <=5) %>% 
  select(-week) %>% 
  group_by(weeks_since)
```

```{r long_bike}
dt_most %>% 
  filter(type == "B") %>% 
  slice_max(time, n = 2) %>% 
  my_kable(caption = "Longest bike rides")
```

```{r long_foot}
dt_most %>% 
  filter(type == "F") %>% 
  slice_max(time, n = 2) %>% 
  my_kable(caption = "Longest walks")
```

```{r long_run}
dt_most %>% 
  filter(type == "R") %>% 
  slice_max(time, n = 2) %>% 
  my_kable(caption = "Longest runs")
```

Longest activities in last 12 weeks:

```{r long}
dt %>% 
  mutate(weeks_since = isoweek(end_date) - isoweek(date)) %>%
  filter(weeks_since <=11) %>% 
  select(-week) %>% 
  slice_max(time, n = 10) %>% 
  my_kable(caption = "10 longest activities in last 12 weeks")
```

