---
title: "Shoes"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, error = FALSE, cache = FALSE)
library(tidyverse)
library(edwards)
library(knitr)
library(kableExtra)
library(reactable)
options(dplyr.summarise.inform = FALSE)
```

```{r shoes}
shoes <- readRDS("../data_processed/shoes.RDS")
```

Experimenting with table formats. 

```{r owned}
shoes %>% 
  filter(owned) %>% 
  group_by(id, name) %>% 
  summarise(dist_run = sum(distance * (type %in% "R")),
            dist_walk = sum(distance * (type %in% "F")),
            dist_all = sum(distance * (type %in% c("F", "R")))) %>% 
  arrange(desc(dist_all)) %>% 
  reactable()  
```

```{r owned_dt}
shoes %>% 
  filter(owned) %>% 
  group_by(id, name) %>% 
  summarise(dist_run = sum(distance * (type %in% "R")),
            dist_walk = sum(distance * (type %in% "F")),
            dist_all = sum(distance * (type %in% c("F", "R")))) %>% 
  arrange(desc(dist_all)) %>% 
  DT::datatable(caption = "Using DT package")  
```

Just running:

```{r owned2}
shoes %>% 
  filter(owned) %>% 
  group_by(id, name, year) %>% 
  summarise(dist = sum(distance)) %>% 
  arrange(desc(dist)) %>% 
  reactable(groupBy = "year", 
            columns = list(dist = colDef(aggregate = "sum")))  
#  scroll_box(width = "100%", height = "400px")
```

Just 2021: 

```{r run_2021}
shoes %>% 
  filter(year == 2021) %>% 
  filter(owned) %>% 
  group_by(id, name) %>% 
  summarise(dist_run = sum(distance * (type %in% "R")),
            dist_walk = sum(distance * (type %in% "F")),
            dist_all = sum(distance * (type %in% c("F", "R")))) %>% 
  arrange(desc(dist_all)) %>% 
  my_kable() %>% 
  scroll_box(width = "100%", height = "400px")
```  

Just 2022: 

```{r run_2022}
shoes %>% 
  filter(year == 2022) %>% 
  filter(owned) %>% 
  group_by(id, name) %>% 
  summarise(dist_run = sum(distance * (type %in% "R")),
            dist_walk = sum(distance * (type %in% "F")),
            dist_all = sum(distance * (type %in% c("F", "R")))) %>% 
  arrange(desc(dist_all)) %>% 
  my_kable() %>% 
  scroll_box(width = "100%", height = "400px")
```  

Just 2023: 

```{r run_2023}
shoes %>% 
  filter(year == 2023) %>% 
  filter(owned) %>% 
  group_by(id, name) %>% 
  summarise(dist_run = sum(distance * (type %in% "R")),
            dist_walk = sum(distance * (type %in% "F")),
            dist_all = sum(distance * (type %in% c("F", "R")))) %>% 
  arrange(desc(dist_all)) %>% 
  my_kable() %>% 
  scroll_box(width = "100%", height = "400px")
```  
